version: '3'

services:
  test:
    image: node:12.14.0-alpine
    environment:
      - AWS_ENDPOINT_SNS=http://localstack:4566
    ports:
      - 4566:4566
    depends_on:
      - terraform
      - localstack
    volumes:
      - ./:/opt/work
    working_dir: /opt/work
    command: sh -c "yarn jest -i --ci --runInBand"
