version: '3'

services:
  localstack:
    image: localstack/localstack:0.11.4
    environment:
      - EDGE_PORT=4566
      - HOSTNAME=localstack
      - HOSTNAME_EXTERNAL=localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
  terraform:
    image: hashicorp/terraform:0.12.29
    environment:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    depends_on:
      - localstack
    volumes:
      - ./tools/terraform:/tmp/tools/terraform
    working_dir: /opt/work
    entrypoint: sh
    command: >
      -c " cp -R /tmp/tools/terraform/* /opt/work/ &&  terraform init &&
      terraform apply -auto-approve -backup="-" -no-color && cp -R
      /opt/work/.terraform /opt/work/terraform.tfstate /tmp/tools/terraform/ "
