integrations:
  - projectName: graph-azure
    displayName: Azure
    knowledgeCategoriesPaths: cloud-service-provider
  - projectName: graph-microsoft-365
    displayName: Microsoft 365
    knowledgeCategoriesPaths: identity_and-access-management
