integrations:
  - projectName: graph-airwatch
    displayName: AirWatch
  - projectName: graph-artifactory
    displayName: JFrog Artifactory
  - projectName: graph-auth0
    displayName: Auth0
  - projectName: graph-azure
    displayName: Azure
  - projectName: graph-azure-devops
    displayName: Azure DevOps
