export const expectedSortedChanges = [
  {
  "childrenPath": "getting-started_and-admin/jupiterOne-query-language_(J1QL)-copy.md",
  "description": "",
  "fileName": "getting-started_and-admin",
  "knowledgeBaseID": 1,
  "knowledgeCategoryID": null,
  "name": "Getting Started and Admin",
  "parentID": null,
  "path": "getting-started_and-admin",
  "procedureType": "Category",
},
{
  "articleID": null,
  "body": "FILE_DOES_NOT_EXIST",
  "fileName": "jupiterOne-query-language_(J1QL)-copy.md",
  "format": "markdown",
  "knowledgeCategoryID": null,
  "locale": "en",
  "name": "JupiterOne Query Language (J1QL) Copy",
  "path": "getting-started_and-admin/jupiterOne-query-language_(J1QL)-copy.md",
  "procedureType": "Article",
},
{
  "articleID": null,
  "body": "FILE_DOES_NOT_EXIST",
  "fileName": "jupiterOne-query-language_(J1QL).md",
  "format": "markdown",
  "knowledgeCategoryID": null,
  "locale": "en",
  "name": "JupiterOne Query Language (J1QL)",
  "path": "getting-started_and-admin/jupiterOne-query-language_(J1QL).md",
  "procedureType": "Article",
},
{
  "childrenPath": "getting-started_and-admin/compliance-reporting/soc2-with-jupiterone-copy.md",
  "description": "",
  "fileName": "compliance-reporting",
  "knowledgeBaseID": 1,
  "knowledgeCategoryID": null,
  "name": "Compliance Reporting",
  "parentID": null,
  "path": "getting-started_and-admin/compliance-reporting",
  "procedureType": "Category",
},
{
  "articleID": null,
  "body": "FILE_DOES_NOT_EXIST",
  "fileName": "soc2-with-jupiterone-copy.md",
  "format": "markdown",
  "knowledgeCategoryID": null,
  "locale": "en",
  "name": "Soc2 With Jupiterone Copy",
  "path": "getting-started_and-admin/compliance-reporting/soc2-with-jupiterone-copy.md",
  "procedureType": "Article",
},
{
  "articleID": null,
  "body": "FILE_DOES_NOT_EXIST",
  "fileName": "soc2-with-jupiterone.md",
  "format": "markdown",
  "knowledgeCategoryID": null,
  "locale": "en",
  "name": "Soc2 With Jupiterone",
  "path": "getting-started_and-admin/compliance-reporting/soc2-with-jupiterone.md",
  "procedureType": "Article",
}
];

export const expectHandleNestedKnowledgeCategoryChanges = [
  
{
 "childrenPath": "getting-started_and-admin/compliance-reporting/soc2-with-jupiterone-copy.md",
 "description": "",
 "fileName": "getting-started_and-admin",
 "knowledgeBaseID": 1,
 "knowledgeCategoryID": null,
 "name": "Getting Started and Admin",
 "parentID": null,
 "path": "getting-started_and-admin",
 "procedureType": "Category",
},
{
 "childrenPath": "getting-started_and-admin/compliance-reporting/soc2-with-jupiterone-copy.md",
 "description": "",
 "fileName": "compliance-reporting",
 "knowledgeBaseID": 1,
 "knowledgeCategoryID": null,
 "name": "Compliance Reporting",
 "parentID": null,
 "path": "getting-started_and-admin/compliance-reporting",
 "procedureType": "Category",
},
{
 "articleID": null,
 "body": "FILE_DOES_NOT_EXIST",
 "fileName": "soc2-with-jupiterone-copy.md",
 "format": "markdown",
 "knowledgeCategoryID": null,
 "locale": "en",
 "name": "Soc2 With Jupiterone Copy",
 "path": "getting-started_and-admin/compliance-reporting/soc2-with-jupiterone-copy.md",
 "procedureType": "Article",
},
{
 "articleID": null,
 "body": "FILE_DOES_NOT_EXIST",
 "fileName": "soc2-with-jupiterone.md",
 "format": "markdown",
 "knowledgeCategoryID": null,
 "locale": "en",
 "name": "Soc2 With Jupiterone",
 "path": "getting-started_and-admin/compliance-reporting/soc2-with-jupiterone.md",
 "procedureType": "Article",
},
{
 "articleID": null,
 "body": "FILE_DOES_NOT_EXIST",
 "fileName": "jupiterOne-query-language_(J1QL)-copy.md",
 "format": "markdown",
 "knowledgeCategoryID": null,
 "locale": "en",
 "name": "JupiterOne Query Language (J1QL) Copy",
 "path": "getting-started_and-admin/jupiterOne-query-language_(J1QL)-copy.md",
 "procedureType": "Article",
},
{
 "articleID": null,
 "body": "FILE_DOES_NOT_EXIST",
 "fileName": "jupiterOne-query-language_(J1QL).md",
 "format": "markdown",
 "knowledgeCategoryID": null,
 "locale": "en",
 "name": "JupiterOne Query Language (J1QL)",
 "path": "getting-started_and-admin/jupiterOne-query-language_(J1QL).md",
 "procedureType": "Article",
},
{
 "childrenPath": "rock-and-roll/rocks.md",
 "description": "",
 "fileName": "rock-and-roll",
 "knowledgeBaseID": 1,
 "knowledgeCategoryID": null,
 "name": "Rock And Roll",
 "parentID": null,
 "path": "rock-and-roll",
 "procedureType": "Category",
},
{
 "articleID": null,
 "body": "FILE_DOES_NOT_EXIST",
 "fileName": "rocks.md",
 "format": "markdown",
 "knowledgeCategoryID": null,
 "locale": "en",
 "name": "Rocks",
 "path": "rock-and-roll/rocks.md",
 "procedureType": "Article",
},

];
