// import { VanillaKnowledgeCategory } from './types';
// export const getKnowledgeCategoryReturn: { data: VanillaKnowledgeCategory[] } =
//   {
//     data: [
//       {
//         knowledgeCategoryID: 1,
//         name: 'JupiterOne Product Documentation',
//         parentID: -1,
//         knowledgeBaseID: 1,
//         sortChildren: null,
//         sort: 0,
//         insertUserID: 10,
//         dateInserted: '2021-10-25T14:48:46+00:00',
//         updateUserID: 10,
//         dateUpdated: '2021-11-04T18:38:15+00:00',
//         lastUpdatedArticleID: null,
//         lastUpdatedUserID: null,
//         articleCount: 1,
//         articleCountRecursive: 3,
//         childCategoryCount: 6,
//         url: 'https://jupiterone.vanillastaging.com/kb/categories/1-jupiterone-product-documentation',
//         foreignID: null,
//       },
//       {
//         knowledgeCategoryID: 2,
//         name: 'Getting Started and Admin',
//         parentID: 1,
//         knowledgeBaseID: 1,
//         sortChildren: null,
//         sort: 1,
//         insertUserID: 10,
//         dateInserted: '2021-10-26T15:15:37+00:00',
//         updateUserID: 10,
//         dateUpdated: '2021-10-26T17:07:41+00:00',
//         lastUpdatedArticleID: null,
//         lastUpdatedUserID: null,
//         articleCount: 1,
//         articleCountRecursive: 1,
//         childCategoryCount: 0,
//         url: 'https://jupiterone.vanillastaging.com/kb/categories/2-getting-started-and-admin',
//         foreignID: null,
//       },
//       {
//         knowledgeCategoryID: 3,
//         name: 'Release Notes',
//         parentID: 1,
//         knowledgeBaseID: 1,
//         sortChildren: null,
//         sort: 0,
//         insertUserID: 10,
//         dateInserted: '2021-10-26T16:58:43+00:00',
//         updateUserID: 10,
//         dateUpdated: '2021-10-26T17:07:41+00:00',
//         lastUpdatedArticleID: null,
//         lastUpdatedUserID: null,
//         articleCount: 0,
//         articleCountRecursive: 0,
//         childCategoryCount: 0,
//         url: 'https://jupiterone.vanillastaging.com/kb/categories/3-release-notes',
//         foreignID: null,
//       },
//       {
//         knowledgeCategoryID: 4,
//         name: 'Asset Management',
//         parentID: 1,
//         knowledgeBaseID: 1,
//         sortChildren: null,
//         sort: 2,
//         insertUserID: 10,
//         dateInserted: '2021-10-26T16:59:27+00:00',
//         updateUserID: 10,
//         dateUpdated: '2021-10-26T17:07:41+00:00',
//         lastUpdatedArticleID: null,
//         lastUpdatedUserID: null,
//         articleCount: 0,
//         articleCountRecursive: 0,
//         childCategoryCount: 0,
//         url: 'https://jupiterone.vanillastaging.com/kb/categories/4-asset-management',
//         foreignID: null,
//       },
//       {
//         knowledgeCategoryID: 6,
//         name: 'Security Operations',
//         parentID: 1,
//         knowledgeBaseID: 1,
//         sortChildren: null,
//         sort: 3,
//         insertUserID: 10,
//         dateInserted: '2021-10-26T17:04:46+00:00',
//         updateUserID: 10,
//         dateUpdated: '2021-10-26T17:07:41+00:00',
//         lastUpdatedArticleID: null,
//         lastUpdatedUserID: null,
//         articleCount: 0,
//         articleCountRecursive: 0,
//         childCategoryCount: 0,
//         url: 'https://jupiterone.vanillastaging.com/kb/categories/6-security-operations',
//         foreignID: null,
//       },
//       {
//         knowledgeCategoryID: 7,
//         name: 'Compliance and Reporting',
//         parentID: 1,
//         knowledgeBaseID: 1,
//         sortChildren: null,
//         sort: 4,
//         insertUserID: 10,
//         dateInserted: '2021-10-26T17:05:24+00:00',
//         updateUserID: 12,
//         dateUpdated: '2021-11-03T16:50:22+00:00',
//         lastUpdatedArticleID: null,
//         lastUpdatedUserID: null,
//         articleCount: 1,
//         articleCountRecursive: 1,
//         childCategoryCount: 0,
//         url: 'https://jupiterone.vanillastaging.com/kb/categories/7-compliance-and-reporting',
//         foreignID: null,
//       },
//       {
//         knowledgeCategoryID: 8,
//         name: 'APIs and Integrations',
//         parentID: 1,
//         knowledgeBaseID: 1,
//         sortChildren: null,
//         sort: 5,
//         insertUserID: 10,
//         dateInserted: '2021-10-26T17:06:41+00:00',
//         updateUserID: 10,
//         dateUpdated: '2021-10-26T17:07:41+00:00',
//         lastUpdatedArticleID: null,
//         lastUpdatedUserID: null,
//         articleCount: 0,
//         articleCountRecursive: 0,
//         childCategoryCount: 0,
//         url: 'https://jupiterone.vanillastaging.com/kb/categories/8-apis-and-integrations',
//         foreignID: null,
//       },
//     ],
//   };
